const gyozaImage = new URL('../static/img/gyoza.jpg', import.meta.url);
const meatImage = new URL('../static/img/meat.jpg', import.meta.url);
const saladImage = new URL('../static/img/salad.jpg', import.meta.url);
const donutImage = new URL('../static/img/donut.jpg', import.meta.url);
const drinkImage = new URL('../static/img/drink.jpg', import.meta.url);
const pastaImage = new URL('../static/img/pasta.jpg', import.meta.url);


const menuContent = {
    'popular': {
        title: 'Popular',
        items: [
            { name: 'Gyoza', 
              description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi, velit',
              price: '30$',
              image: gyozaImage,
            },
            { name: 'Meat', 
              description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi, velit',
              price: '40$',
              image: meatImage,
            },
            { name: 'Salad', 
              description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi, velit',
              price: '15$',
              image: saladImage,
            },
            { name: 'Donut', 
              description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi, velit',
              price: '10$',
              image: donutImage
            },
            { name: 'Gyoza', 
              description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi, velit',
              price: '30$',
              image: gyozaImage,
            },
            { name: 'Meat', 
              description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi, velit',
              price: '40$',
              image: meatImage,
            },
            { name: 'Salad', 
              description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi, velit',
              price: '15$',
              image: saladImage,
            },
            { name: 'Donut', 
              description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi, velit',
              price: '10$',
              image: donutImage
            }
        ]
    },

    'main_dishes': {
      title: 'Main Dishes',
      items: [
          { name: 'Meat', 
            description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi, velit',
            price: '30$',
            image: meatImage,
          },
          { name: 'Meat', 
            description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi, velit',
            price: '40$',
            image: meatImage,
          },
          { name: 'Meat', 
            description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi, velit',
            price: '15$',
            image: meatImage,
          },
          { name: 'Meat', 
            description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi, velit',
            price: '10$',
            image: meatImage
          },
          { name: 'Meat', 
            description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi, velit',
            price: '30$',
            image: meatImage,
          },
          { name: 'Meat', 
            description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi, velit',
            price: '40$',
            image: meatImage,
          },
          { name: 'Meat', 
            description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi, velit',
            price: '15$',
            image: meatImage,
          },
          { name: 'Meat', 
            description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi, velit',
            price: '10$',
            image: meatImage
          }
      ]
    },
    'drinks': {
      title: 'Drinks',
      items: [
        { name: 'Cola', 
            description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi, velit',
            price: '30$',
            image: drinkImage,
          },
          { name: 'Cola', 
            description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi, velit',
            price: '40$',
            image: drinkImage,
          },
          { name: 'Cola', 
            description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi, velit',
            price: '15$',
            image: drinkImage,
          },
          { name: 'Cola', 
            description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi, velit',
            price: '10$',
            image: drinkImage
          },
          { name: 'Cola', 
            description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi, velit',
            price: '30$',
            image: drinkImage,
          },
          { name: 'Cola', 
            description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi, velit',
            price: '40$',
            image: drinkImage,
          },
          { name: 'Cola', 
            description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi, velit',
            price: '15$',
            image: drinkImage,
          },
          { name: 'Meat', 
            description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi, velit',
            price: '10$',
            image: drinkImage,
          }
      ]
    },
    'sweets': {
      title: 'Sweets',
      items: [
        { name: 'Donut', 
            description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi, velit',
            price: '30$',
            image: donutImage,
          },
          { name: 'Donut', 
            description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi, velit',
            price: '40$',
            image: donutImage,
          },
          { name: 'Donut', 
            description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi, velit',
            price: '15$',
            image: donutImage,
          },
          { name: 'Donut', 
            description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi, velit',
            price: '10$',
            image: donutImage
          },
          { name: 'Donut', 
            description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi, velit',
            price: '30$',
            image: donutImage,
          },
          { name: 'Donut', 
            description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi, velit',
            price: '40$',
            image: donutImage,
          },
          { name: 'Donut', 
            description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi, velit',
            price: '15$',
            image: donutImage,
          },
          { name: 'Donut', 
            description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi, velit',
            price: '10$',
            image: donutImage,
          }
      ]
    },
    'pasta': {
      title: 'Pasta',
      items: [
        { name: 'Baloney', 
            description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi, velit',
            price: '30$',
            image: pastaImage,
          },
          { name: 'Baloney', 
            description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi, velit',
            price: '40$',
            image: pastaImage,
          },
          { name: 'Baloney', 
            description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi, velit',
            price: '15$',
            image: pastaImage,
          },
          { name: 'Baloney', 
            description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi, velit',
            price: '10$',
            image: pastaImage
          },
          { name: 'Baloney', 
            description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi, velit',
            price: '30$',
            image: pastaImage,
          },
          { name: 'Baloney', 
            description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi, velit',
            price: '40$',
            image: pastaImage,
          },
          { name: 'Baloney', 
            description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi, velit',
            price: '15$',
            image: pastaImage,
          },
          { name: 'Baloney', 
            description: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi, velit',
            price: '10$',
            image: pastaImage,
          }
      ]
    }
};

export default menuContent;